repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-added-large-files
      - id: check-ast
      - id: check-case-conflict
      - id: check-executables-have-shebangs
        exclude: ^assets/
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-yaml
      - id: debug-statements
      - id: destroyed-symlinks
      - id: end-of-file-fixer
        exclude: tests/test_changes/
        files: \.(py|sh|rst|yml|yaml)$
      - id: mixed-line-ending
      - id: trailing-whitespace
        files: \.(py|sh|rst|yml|yaml)$
  # - repo: https://github.com/asottile/setup-cfg-fmt
  #   rev: v1.20.1
  #   hooks:
  #     - id: setup-cfg-fmt
  - repo: https://github.com/asottile/pyupgrade
    rev: v2.34.0
    hooks:
      - id: pyupgrade
        args: [--py310-plus]
  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
  - repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort
  - repo: https://github.com/PyCQA/flake8
    rev: 4.0.1
    hooks:
      - id: flake8
  # - repo: https://github.com/pre-commit/mirrors-mypy
  #   rev: v0.960
  #   hooks:
  #     - id: mypy
  #       additional_dependencies:
  #         - ...
  #       files: ^pokete/
  #       args: [--strict]
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.31.1
    hooks:
      - id: markdownlint-fix
        args: [
          --disable=MD013,
          --disable=MD014,
          --disable=MD024,
          --disable=MD033,
          --disable=MD041,
        ]
        exclude: ^.github/ISSUE_TEMPLATE/
  - repo: https://github.com/pecigonzalo/pre-commit-shfmt
    rev: v2.1.0
    hooks:
      - id: shell-fmt-docker
  - repo: https://github.com/koalaman/shellcheck-precommit
    rev: v0.8.0
    hooks:
      - id: shellcheck
