// DO NOT EDIT!
// This code was auto generated by the `protoc-gen-pokete-resources` plugin,
// part of the pokete project, by <lxgr@protonmail.com>

package base

type Achievement struct {
	Title string `json:"title"`
	Desc  string `json:"desc"`
}
