// DO NOT EDIT!
// This code was auto generated by the `protoc-gen-pokete-resources` plugin,
// part of the pokete project, by <lxgr@protonmail.com>

package base

type Item struct {
	PrettyName string  `json:"pretty_name"`
	Desc       string  `json:"desc"`
	Price      int32   `json:"price"`
	Fn         *string `json:"fn"`
}
