# DO NOT EDIT!
# This code was auto generated by the `protoc-gen-pokete-resources-python` plugin,
# part of the pokete project, by <lxgr@protonmail.com>
from typing import TypedDict


class NatureDict(TypedDict):
    esc: str
    atc: float
    def: float
    

class Nature:
    def __init__(
        self,
        esc: str,
        atc: float,
        def: float
    ):
        self.esc: str = esc
        self.atc: float = atc
        self.def: float = def
        
    @classmethod
    def from_dict(cls, _d: NatureDict | None) -> "Nature" | None:
        if _d is None:
            return None
        return cls(
            esc=_d["esc"],
            atc=_d["atc"],
            def=_d["def"],
        )
