// DO NOT EDIT!
// This code was auto generated by the `protoc-gen-pokete-resources` plugin,
// part of the pokete project, by <lxgr@protonmail.com>

package base

type Nature struct {
	Esc  *string  `json:"esc"`
	Atc  *float32 `json:"atc"`
	Def  *float32 `json:"def_"`
	Init *float32 `json:"init"`
}
