// DO NOT EDIT!
// This code was auto generated by the `protoc-gen-pokete-resources` plugin,
// part of the pokete project, by <lxgr@protonmail.com>

package base

type Type struct {
	Effective   []string `json:"effective"`
	Ineffective []string `json:"ineffective"`
	Color       []string `json:"color"`
}
