// DO NOT EDIT!
// This code was auto generated by the `protoc-gen-pokete-resources` plugin,
// part of the pokete project, by <lxgr@protonmail.com>

package base

type Weather struct {
	Info     string             `json:"info"`
	Effected map[string]float32 `json:"effected"`
}
