// DO NOT EDIT!
// This code was auto generated by the `protoc-gen-pokete-resources` plugin,
// part of the pokete project, by <lxgr@protonmail.com>

package resources

type Coords struct {
	X int32 `json:"x"`
	Y int32 `json:"y"`
}
