// DO NOT EDIT!
// This code was auto generated by the `protoc-gen-pokete-resources` plugin,
// part of the pokete project, by <lxgr@protonmail.com>

package resources

type Chat struct {
	Q []string        `json:"q"`
	A map[string]Chat `json:"a"`
}

type NPC struct {
	Texts []string `json:"texts"`
	Fn    *string  `json:"fn"`
	Map   string   `json:"map"`
	X     int32    `json:"x"`
	Y     int32    `json:"y"`
	Chat  *Chat    `json:"chat"`
}
