// DO NOT EDIT!
// This code was auto generated by the `protoc-gen-pokete-resources` plugin,
// part of the pokete project, by <lxgr@protonmail.com>

package resources

type DorArgs struct {
	X   int32  `json:"x"`
	Y   int32  `json:"y"`
	Map string `json:"map"`
}

type Dor struct {
	X    int32   `json:"x"`
	Y    int32   `json:"y"`
	Args DorArgs `json:"args"`
}

type SpecialDors struct {
	Dor     *Coords `json:"dor"`
	Shopdor *Coords `json:"shopdor"`
}

type Ob struct {
	X   int32   `json:"x"`
	Y   int32   `json:"y"`
	Txt string  `json:"txt"`
	Cls *string `json:"cls"`
}

type Obmap struct {
	HardObs     map[string]Ob     `json:"hard_obs"`
	SoftObs     map[string]Ob     `json:"soft_obs"`
	Dors        map[string]Dor    `json:"dors"`
	SpecialDors *SpecialDors      `json:"special_dors"`
	Balls       map[string]Coords `json:"balls"`
}
