// DO NOT EDIT!
// This code was auto generated by the `protoc-gen-pokete-resources` plugin,
// part of the pokete project, by <lxgr@protonmail.com>

package resources

import ()

type PokeArgs struct {
	Pokes  []string `json:"pokes"`
	Minlvl int32    `json:"minlvl"`
	Maxlvl int32    `json:"maxlvl"`
}

type Map struct {
	Height       int32     `json:"height"`
	Width        int32     `json:"width"`
	Song         string    `json:"song"`
	PrettyName   string    `json:"pretty_name"`
	ExtraActions *string   `json:"extra_actions"`
	PokeArgs     *PokeArgs `json:"poke_args"`
	WPokeArgs    *PokeArgs `json:"w_poke_args"`
	Weather      *string   `json:"weather"`
}
