// DO NOT EDIT!
// This code was auto generated by the `protoc-gen-pokete-resources` plugin,
// part of the pokete project, by <lxgr@protonmail.com>

package resources

import ()

type TrackInfo struct {
	Name string `json:"name"`
	Hash []byte `json:"hash"`
}

type Track struct {
	Info    TrackInfo `json:"info"`
	Content []byte    `json:"content"`
}
