# DO NOT EDIT!
# This code was auto generated by the `protoc-gen-pokete-resources-python` plugin,
# part of the pokete project, by <lxgr@protonmail.com>
from typing import TypedDict


class ItemDict(TypedDict):
    pretty_name: str
    desc: str
    price: int
    fn: str | None


class Item:
    def __init__(
        self,
        pretty_name: str,
        desc: str,
        price: int,
        fn: str | None
    ):
        self.pretty_name: str = pretty_name
        self.desc: str = desc
        self.price: int = price
        self.fn: str | None = fn

    @classmethod
    def from_dict(cls, _d: ItemDict | None) -> "Item | None":
        if _d is None:
            return None
        return cls(
            pretty_name=_d["pretty_name"],
            desc=_d["desc"],
            price=_d["price"],
            fn=_d.get("fn", None),
        )

    def to_dict(self) -> ItemDict:
        ret: ItemDict = {}
        
        ret["pretty_name"] = self.pretty_name
        ret["desc"] = self.desc
        ret["price"] = self.price
        if self.fn is not None:
            ret["fn"] = self.fn
        
        return ret
