// DO NOT EDIT!
// This code was auto generated by the `protoc-gen-pokete-resources` plugin,
// part of the pokete project, by <lxgr@protonmail.com>

package base

import ()

type Attack struct {
	Name        string   `json:"name"`
	Factor      float32  `json:"factor"`
	Action      *string  `json:"action"`
	WorldAction string   `json:"world_action"`
	Move        []string `json:"move"`
	MissChance  float32  `json:"miss_chance"`
	MinLvl      int32    `json:"min_lvl"`
	Desc        string   `json:"desc"`
	Types       []string `json:"types"`
	Effect      *string  `json:"effect"`
	IsGeneric   bool     `json:"is_generic"`
	Ap          int32    `json:"ap"`
}
