# DO NOT EDIT!
# This code was auto generated by the `protoc-gen-pokete-resources-python` plugin,
# part of the pokete project, by <lxgr@protonmail.com>


from .assets import (
    Assets,
    AssetsDict,
    BaseAssets,
    BaseAssetsDict,
    MapTrainers,
    MapTrainersDict,
)
from .coords import (
    Coords,
    CoordsDict,
)
from .maps import (
    Map,
    MapDict,
    PokeArgs,
    PokeArgsDict,
)
from .npcs import (
    NPC,
    Chat,
    ChatDict,
    NPCDict,
)
from .obmaps import (
    Dor,
    DorArgs,
    DorArgsDict,
    DorDict,
    Ob,
    ObDict,
    Obmap,
    ObmapDict,
    SpecialDors,
    SpecialDorsDict,
)
from .stations import (
    Decoration,
    DecorationDict,
    DecorationGen,
    DecorationGenDict,
    Station,
    StationDict,
    StationGen,
    StationGenDict,
)
from .trainers import (
    Trainer,
    TrainerArgs,
    TrainerArgsDict,
    TrainerDict,
    TrainerPokeArgs,
    TrainerPokeArgsDict,
)

__all__ = [
    "TrainerPokeArgs",
    "TrainerPokeArgsDict",
    "TrainerArgs",
    "TrainerArgsDict",
    "Trainer",
    "TrainerDict",
    "Chat",
    "ChatDict",
    "NPC",
    "NPCDict",
    "Coords",
    "CoordsDict",
    "DorArgs",
    "DorArgsDict",
    "Dor",
    "DorDict",
    "SpecialDors",
    "SpecialDorsDict",
    "Ob",
    "ObDict",
    "Obmap",
    "ObmapDict",
    "StationGen",
    "StationGenDict",
    "Station",
    "StationDict",
    "DecorationGen",
    "DecorationGenDict",
    "Decoration",
    "DecorationDict",
    "PokeArgs",
    "PokeArgsDict",
    "Map",
    "MapDict",
    "BaseAssets",
    "BaseAssetsDict",
    "MapTrainers",
    "MapTrainersDict",
    "Assets",
    "AssetsDict",
]
