#!/usr/bin/env bash
# shellcheck disable=SC2034,2154
pokecount=1

wpoke1(){
enemyap="$((enemylvl + 20))"
enemypoke="Steini          "
enemyhp="$((enemylvl * 2))"
enemyatk=$((5 + enemylvl))
enemydef=$((1 + 1 * enemylvl / 3))
enemyatc1=atc1

epokeico1=" +-------+ "
epokeico2=" | o   o | "
epokeico3=" |  www  | "
epokeico4=" +-------+ "
}

wpoke2(){
enemyap="$((enemylvl + 20))"
enemypoke="Vogli           "
enemyhp="$((enemylvl * 2))"

epokeico1="    A      "
epokeico2="   <')     "
epokeico3="    www*   "
epokeico4="    ||     "
}

wpoke3(){
enemyap="$((enemylvl + 5))"
enemypoke="Karpi           "
enemyhp="$((enemylvl * 3 / 2))"

epokeico1="           "
epokeico2="           "
epokeico3="  <°))))>< "
epokeico4="           "
}


wpoke4(){
enemyap="$((enemylvl + 5))"
enemypoke="Würgos          "
enemyhp="$((enemylvl * 3 / 2))"

epokeico1=" {{{{{{{{{ "
epokeico2="  }}}}}}}  "
epokeico3="  >'({{{   "
epokeico4="           "
}
