# DO NOT EDIT!
# This code was auto generated by the `protoc-gen-pokete-resources-python` plugin,
# part of the pokete project, by <lxgr@protonmail.com>


from .assets import (BaseAssets, BaseAssetsDict, )
from .coords import (Coords, CoordsDict, )
from .maps import (PokeArgs, PokeArgsDict, Map, MapDict, )
from .npcs import (Chat, ChatDict, NPC, NPCDict, )
from .obmaps import (DorArgs, DorArgsDict, Dor, DorDict, SpecialDors, SpecialDorsDict, Ob, ObDict, Obmap, ObmapDict, )
from .stations import (StationGen, StationGenDict, Station, StationDict, DecorationGen, DecorationGenDict, Decoration, DecorationDict, )
from .trainers import (TrainerPokeArgs, TrainerPokeArgsDict, TrainerArgs, TrainerArgsDict, Trainer, TrainerDict, )
