# DO NOT EDIT!
# This code was auto generated by the `protoc-gen-pokete-resources-python` plugin,
# part of the pokete project, by <lxgr@protonmail.com>
from typing import TypedDict
from .base.items import (Item, ItemDict, )


class BaseAssetsDict(TypedDict):
    items: dict[str, "ItemDict"]
    

class BaseAssets:
    def __init__(
        self,
        items: dict[str, "Item"]
    ):
        self.items: dict[str, "Item"] = items
        
    @classmethod
    def from_dict(cls, _d: BaseAssetsDict | None) -> "BaseAssets" | None:
        if _d is None:
            return None
        return cls(
            items={i: item for i, item in _d["items"].items()},
        )
