# DO NOT EDIT!
# This code was auto generated by the `protoc-gen-pokete-resources-python` plugin,
# part of the pokete project, by <lxgr@protonmail.com>
from typing import TypedDict
from .coords import (Coords, CoordsDict, )


class StationGenDict(TypedDict):
    additionals: list[str]
    desc: str
    text: str
    color: str
    a_next: str | None
    w_next: str | None
    s_next: str | None
    d_next: str | None
    

class StationGen:
    def __init__(
        self,
        additionals: list[str],
        desc: str,
        text: str,
        color: str,
        a_next: str | None,
        w_next: str | None,
        s_next: str | None,
        d_next: str | None
    ):
        self.additionals: list[str] = additionals
        self.desc: str = desc
        self.text: str = text
        self.color: str = color
        self.a_next: str | None = a_next
        self.w_next: str | None = w_next
        self.s_next: str | None = s_next
        self.d_next: str | None = d_next
        
    @classmethod
    def from_dict(cls, _d: StationGenDict | None) -> "StationGen" | None:
        if _d is None:
            return None
        return cls(
            additionals=_d["additionals"],
            desc=_d["desc"],
            text=_d["text"],
            color=_d["color"],
            a_next=_d.get("a_next", None),
            w_next=_d.get("w_next", None),
            s_next=_d.get("s_next", None),
            d_next=_d.get("d_next", None),
        )


class StationDict(TypedDict):
    gen: "StationGenDict"
    add: "CoordsDict"
    

class Station:
    def __init__(
        self,
        gen: "StationGen",
        add: "Coords"
    ):
        self.gen: "StationGen" = gen
        self.add: "Coords" = add
        
    @classmethod
    def from_dict(cls, _d: StationDict | None) -> "Station" | None:
        if _d is None:
            return None
        return cls(
            gen=StationGen.from_dict(_d["gen"]),
            add=Coords.from_dict(_d["add"]),
        )
