name: pytest

on:
  push:

jobs:
  pytest:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Pytest
        run: pip install pytest scrap_engine

      - name: Run Pytest
        run: |
          cd src
          python -m pytest tests -v
